In [32]:
import pandas as pd
import numpy as np

# modules for Log Reg
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

In [23]:
data = pd.read_csv("gs://ukbb_spleen/CHIPCAD_pheno_v4.csv", sep='\s+')

In [36]:
data = pd.read_csv("/medpop/esp2/btruong/Projects/UKBB/ukb_phewas.tsv.gz", sep='\s+')

FileNotFoundError: [Errno 2] No such file or directory: './medpop/esp2/btruong/Projects/UKBB/ukb_phewas.tsv.gz'

In [24]:
data

,ID,Filename,age.x,race.x,Sex.x,SmokingStatusv2.x,tchol.x,hdl.x,SBP.x,antihtnbase.x,...,CHIP_10,DNMT3A_10,non_DNMT3A_10,TET2_10,ASXL1_10,JAK2_10,PPM1D_10,TP53_10,SF3B1_10,SRSF2_10
0,1000107,1000107_20201_2_0.zip,49,white,Female,Previous,199.845320,61.059551,153.0,0,...,0,0,0,0,0,0,0,0,0,0
1,1000169,1000169_20201_2_0.zip,59,white,Female,Previous,239.211135,55.220417,130.0,0,...,0,0,0,0,0,0,0,0,0,0
2,1000336,1000336_20201_2_0.zip,42,white,Female,Current,203.750965,70.843000,118.0,0,...,0,0,0,0,0,0,0,0,0,0
3,1000387,1000387_20201_2_0.zip,64,white,Female,Never,268.174786,72.351121,153.0,0,...,0,0,0,0,0,0,0,0,0,0
4,1000408,1000408_20201_2_0.zip,56,white,Female,Never,242.459395,54.911059,113.0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45968,6025819,6025819_20201_2_0.zip,42,white,Male,Previous,191.337972,65.235885,125.0,0,...,0,0,0,0,0,0,0,0,0,0
45969,6025888,6025888_20201_2_0.zip,67,white,Male,Previous,295.978343,NaN,151.0,1,...,0,0,0,0,0,0,0,0,0,0
45970,6025888,6025888_20201_3_0.zip,67,white,Male,Previous,295.978343,NaN,151.0,1,...,0,0,0,0,0,0,0,0,0,0
45971,6026159,6026159_20201_2_0.zip,62,white,Male,Never,139.675173,49.729311,109.0,1,...,0,0,0,0,0,0,0,0,0,0
45972,6026263,6026263_20201_2_0.zip,60,white,Female,Never,216.511986,61.368909,157.0,0,...,0,0,0,0,0,0,0,0,0,0

In [25]:
for elem in ['Coronary_Artery_Disease',  'Coronary_Artery_Disease_INTERMEDIATE', 'Coronary_Artery_Disease_SOFT',  'Coronary_Artery_Disease_HARD']:
    print(data[elem].value_counts(dropna=False))

0    44304
1     1669
Name: Coronary_Artery_Disease, dtype: int64
0    43295
1     2678
Name: Coronary_Artery_Disease_INTERMEDIATE, dtype: int64
0    42724
1     3249
Name: Coronary_Artery_Disease_SOFT, dtype: int64
0    44058
1     1915
Name: Coronary_Artery_Disease_HARD, dtype: int64

In [26]:
#print(data.pce_goff.value_counts(dropna=False))
data.columns

Index(['ID', 'Filename', 'age.x', 'race.x', 'Sex.x', 'SmokingStatusv2.x',
       'tchol.x', 'hdl.x', 'SBP.x', 'antihtnbase.x', 'dm2_prev.x',
       'dm1_prev.x', 'pce_goff.x', 'age.y', 'race.y', 'Sex.y',
       'SmokingStatusv2.y', 'tchol.y', 'hdl.y', 'SBP.y', 'antihtnbase.y',
       'dm2_prev.y', 'dm1_prev.y', 'pce_goff.y', 'genotyping_array', 'PC1',
       'PC2', 'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8', 'PC9', 'PC10',
       'Coronary_Artery_Disease', 'Prev_Coronary_Artery_Disease',
       'Incd_Coronary_Artery_Disease', 'FollowUp_Coronary_Artery_Disease',
       'Coronary_Artery_Disease_HARD', 'Prev_Coronary_Artery_Disease_HARD',
       'Incd_Coronary_Artery_Disease_HARD',
       'FollowUp_Coronary_Artery_Disease_HARD',
       'Coronary_Artery_Disease_INTERMEDIATE',
       'Prev_Coronary_Artery_Disease_INTERMEDIATE',
       'Incd_Coronary_Artery_Disease_INTERMEDIATE',
       'FollowUp_Coronary_Artery_Disease_INTERMEDIATE',
       'Coronary_Artery_Disease_SOFT', 'Prev_Coronary_Artery_Disease_SOFT',
       'Incd_Coronary_Artery_Disease_SOFT',
       'FollowUp_Coronary_Artery_Disease_SOFT', 'composite_mi_cad_stroke',
       'Prev_composite_mi_cad_stroke', 'Incd_composite_mi_cad_stroke',
       'FollowUp_composite_mi_cad_stroke', 'composite_mi_cad_stroke_death',
       'Prev_composite_mi_cad_stroke_death',
       'Incd_composite_mi_cad_stroke_death',
       'FollowUp_composite_mi_cad_stroke_death', 'composite_mi_cad_stroke_hf',
       'Prev_composite_mi_cad_stroke_hf', 'Incd_composite_mi_cad_stroke_hf',
       'FollowUp_composite_mi_cad_stroke_hf', 'CHIP', 'DNMT3A', 'non_DNMT3A',
       'TET2', 'ASXL1', 'JAK2', 'PPM1D', 'TP53', 'SF3B1', 'SRSF2', 'CHIP_10',
       'DNMT3A_10', 'non_DNMT3A_10', 'TET2_10', 'ASXL1_10', 'JAK2_10',
       'PPM1D_10', 'TP53_10', 'SF3B1_10', 'SRSF2_10'],
      dtype='object')

In [27]:
pce_covars = ['hdl.x', 'tchol.x', 'age.x', 'race.x', 'Sex.x', 'SBP.x', 'dm2_prev.x', 'dm1_prev.x', 'antihtnbase.x', 'SmokingStatusv2.x']

data = data[pce_covars]
data.shape

(45973, 10)

In [28]:
filt_data = data.dropna()
filt_data.shape

# would only lose 2000 patients is 'hdl.x' and 'tchol.x'  are removed

(37090, 10)

In [29]:
for elem in pce_covars:
    print(elem)
    print(data[elem].value_counts(dropna=False))

hdl.x
NaN           6711
50.696055       62
52.977571       60
53.248260       60
52.242846       58
              ...
104.833719       1
106.457849       1
21.075019        1
92.614075        1
96.983758        1
Name: hdl.x, Length: 2086, dtype: int64
tchol.x
NaN           2933
198.723897      30
214.694508      30
225.406031      29
207.811290      28
              ...
290.487237       1
126.140757       1
381.090485       1
312.838358       1
314.191800       1
Name: tchol.x, Length: 5518, dtype: int64
age.x
60    2373
61    2301
59    2092
62    2065
58    2059
56    2006
57    1978
55    1956
54    1849
53    1808
63    1764
52    1714
50    1679
51    1624
49    1561
64    1543
48    1463
47    1413
46    1405
65    1374
45    1291
44    1257
43    1237
66    1132
42    1070
41    1038
67     912
68     752
69     741
40     428
70      88
Name: age.x, dtype: int64
race.x
white    44487
asian      625
black      297
other      230
mixed      209
NaN        125
Name: race.x, dtype: int64
Sex.x
Female    23760
Male      22213
Name: Sex.x, dtype: int64
SBP.x
NaN      2391
131.0     992
129.0     990
130.0     970
135.0     957
         ...
227.0       1
222.0       1
69.0        1
248.0       1
82.0        1
Name: SBP.x, Length: 152, dtype: int64
dm2_prev.x
0    44708
1     1265
Name: dm2_prev.x, dtype: int64
dm1_prev.x
0    45826
1      147
Name: dm1_prev.x, dtype: int64
antihtnbase.x
0    41239
1     4734
Name: antihtnbase.x, dtype: int64
SmokingStatusv2.x
Never       27915
Previous    15134
Current      2824
NaN           100
Name: SmokingStatusv2.x, dtype: int64

In [5]:
phenotype = pd.DataFrame(pd.read_excel("gs://ukbb_spleen/UKBB-Phenotype-codes_CAD-related_v2.xlsx"))
phenotype

,Phenotype,Data field,Field name,Data code,Data code definition,Inclusion,Notes
0,Coronary Artery Disease SOFT,20002,"Non-cancer illness code, self-reported",1074,angina,1,NaN
1,Coronary Artery Disease SOFT,20002,"Non-cancer illness code, self-reported",1075,heart attack/myocardial infarction,1,NaN
2,Coronary Artery Disease SOFT,20004,"Operation code, self-reported",1070,coronary angioplasty (ptca) +/- stent,1,NaN
3,Coronary Artery Disease SOFT,20004,"Operation code, self-reported",1095,coronary artery bypass grafts (cabg),1,NaN
4,Coronary Artery Disease SOFT,20004,"Operation code, self-reported",1523,triple heart bypass,1,NaN
...,...,...,...,...,...,...,...
677,Heart Failure,41205,Diagnoses - secondary ICD9,4280,Congestive heart failure,1,NaN
678,Heart Failure,41203,Diagnoses - main ICD9,4281,Left heart failure,1,NaN
679,Heart Failure,41205,Diagnoses - secondary ICD9,4281,Left heart failure,1,NaN
680,Heart Failure,40001,Diagnoses - main ICD9,4289,"Heart failure, unspecified",1,NaN
681,Heart Failure,40002,Diagnoses - secondary ICD9,4289,"Heart failure, unspecified",1,NaN

In [38]:
from google.cloud import storage

storage_client = storage.Client()
bucket = storage_client.get_bucket('ukbb_spleen')

blob = bucket.blob('data_dictionary.txt')
blob = blob.download_as_string()
blob = blob.decode('utf-8')
print(blob)

Data dictionary
ID
Filename: corresponding image file
age: covariates used for calculating pooled cohort equation
race: covariates used for calculating pooled cohort equation
Sex: covariates used for calculating pooled cohort equation
SmokingStatusv2: covariates used for calculating pooled cohort equation
tchol: total cholesterol; covariates used for calculating pooled cohort equation
hdl: covariates used for calculating pooled cohort equation
SBP: covariates used for calculating pooled cohort equation
antihtnbase: baseline use anti-hypertensive medication; covariates used for calculating pooled cohort equation
dm2_prev: prevalent type 2 diabetes; covariates used for calculating pooled cohort equation
dm1_prev: prevalent type 1 diabetes; covariates used for calculating pooled cohort equation
pce_goff: pooled cohort equation
genotypeing_array: technical variable for genetic information
PC1-PC10: principal components for genetic information
from Coronary_Artery_Disease to FollowUp_composite_mi_cad_stroke_death: CAD outcomes using different definitions; with prevalent cases, incident cases, and follow-up time
from CHIP to the end: somatic mutations variables; do not need to use now

In [62]:
print("Number of total rows: %d" %len(data.ID))
print("Number of unique patients: %d" %len(data.ID.unique()))
data_filt = data.sort_values(by = ["ID", "Filename"]).drop_duplicates()
pce_covars = ['age', 'race', 'Sex', 'tchol', 'hdl', 'SBP', 'dm2_prev', 'dm1_prev', 'antihtnbase', 'SmokingStatusv2']
outcomes = ['Coronary_Artery_Disease', 'Coronary_Artery_Disease_INTERMEDIATE', 'Coronary_Artery_Disease_HARD', 'Coronary_Artery_Disease_SOFT']
other= ['pce_goff']

cols_to_keep = pce_covars+outcomes+pce_risk

data_filt = data[cols_to_keep]

Number of total rows: 45973
Number of unique patients: 43543

In [52]:
print(data_filt.shape)

(45973, 15)

In [70]:
for col in pce_covars:
    print(data_filt[col].value_counts(dropna=False))
    print("\n")
    
print(data_filt.shape)
data_dropna = data_filt.dropna()
print(data_dropna.shape)

60    2373
61    2301
59    2092
62    2065
58    2059
56    2006
57    1978
55    1956
54    1849
53    1808
63    1764
52    1714
50    1679
51    1624
49    1561
64    1543
48    1463
47    1413
46    1405
65    1374
45    1291
44    1257
43    1237
66    1132
42    1070
41    1038
67     912
68     752
69     741
40     428
70      88
Name: age, dtype: int64


white    44487
asian      625
black      297
other      230
mixed      209
NaN        125
Name: race, dtype: int64


Female    23760
Male      22213
Name: Sex, dtype: int64


NaN           2933
198.723897      30
214.694508      30
225.406031      29
207.811290      28
              ...
290.487237       1
126.140757       1
381.090485       1
312.838358       1
314.191800       1
Name: tchol, Length: 5518, dtype: int64


NaN           6711
50.696055       62
52.977571       60
53.248260       60
52.242846       58
              ...
104.833719       1
106.457849       1
21.075019        1
92.614075        1
96.983758        1
Name: hdl, Length: 2086, dtype: int64


NaN      2391
131.0     992
129.0     990
130.0     970
135.0     957
         ...
227.0       1
222.0       1
69.0        1
248.0       1
82.0        1
Name: SBP, Length: 152, dtype: int64


0    44708
1     1265
Name: dm2_prev, dtype: int64


0    45826
1      147
Name: dm1_prev, dtype: int64


0    41239
1     4734
Name: antihtnbase, dtype: int64


Never       27915
Previous    15134
Current      2824
NaN           100
Name: SmokingStatusv2, dtype: int64


(45973, 15)
(36025, 15)

In [74]:
np.random.choice(2, 100, p=[0.3, 0.7])

array([1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1])

In [10]:
rad_feats = pd.read_csv("../radiomics/radiomics_spleen.csv", sep='\s+')

In [11]:
rad_feats.shape

(86922, 1)

Calculating AUC for pce risk scores

In [31]:
df = pd.read_csv('CADcohort_rad.csv')
outcomes = ['Coronary_Artery_Disease', 'Coronary_Artery_Disease_INTERMEDIATE', 'Coronary_Artery_Disease_HARD', 'Coronary_Artery_Disease_SOFT']
df.head()

,age.x,tchol.x,hdl.x,SBP.x,dm2_prev.x,dm1_prev.x,antihtnbase.x,original_shape_Elongation,original_shape_Flatness,original_shape_LeastAxisLength,...,race.x_black,race.x_mixed,race.x_other,race.x_white,sex.x_Female,sex.x_Male,smoking.x_Current,smoking.x_Never,smoking.x_Previous,train
0,49,199.845320,61.059551,153.0,0,0,0,0.543486,0.402501,19.589515,...,0,0,0,1,1,0,0,0,1,0
1,59,239.211135,55.220417,130.0,0,0,0,0.516462,0.380680,16.097229,...,0,0,0,1,1,0,0,0,1,1
2,64,268.174786,72.351121,153.0,0,0,0,0.653198,0.395604,15.929838,...,0,0,0,1,1,0,0,1,0,0
3,56,242.459395,54.911059,113.0,0,0,0,0.643589,0.404867,18.445973,...,0,0,0,1,1,0,0,1,0,1
4,61,221.848413,45.978345,145.0,0,0,0,0.674545,0.444059,22.162395,...,0,0,0,1,1,0,0,1,0,1

In [33]:
for outcome in outcomes:
    print(outcome)
    auc = roc_auc_score(df[outcome], df['pce_goff.y'])
    print(auc)

Coronary_Artery_Disease
0.7729932750793042
Coronary_Artery_Disease_INTERMEDIATE
0.7488235248731632
Coronary_Artery_Disease_HARD
0.7613888568312336
Coronary_Artery_Disease_SOFT
0.7301370208351845